version: '3.5'

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql8_q2db_test
    restart: on-failure
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: q2test
      MYSQL_USER: q2user
      MYSQL_PASSWORD: q2test
      MYSQL_DATABASE: test
  postgres:
    image: postgres
    container_name: postgressql_q2db_test
    restart: on-failure
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: "q2user"
      POSTGRES_PASSWORD: "q2test"

